version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-list-aws-deploy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vw0kolu80uxb"
s3_prefix = "todo-list-aws-deploy"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
